name: Deploy to Scalingo

#on:
#  workflow_run:
#    workflows: ['Release']
#    types:
#      - completed

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  SCALINGO_API_URL: https://api.osc-fr1.scalingo.com/v1

jobs:
  deploy:
    name: Deploy to Scalingo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Get app name from package.json
        id: get-app-name
        run: |
          APP_NAME=$(bun -e "console.log(require('./package.json').name)")
          echo "APP_NAME=$APP_NAME" >> $GITHUB_OUTPUT

      - name: Check if app exists on Scalingo
        id: check-app
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer ${{ secrets.SCALINGO_API_TOKEN }}" \
            "${{ env.SCALINGO_API_URL }}/apps/${{ steps.get-app-name.outputs.APP_NAME }}")

          if [ "$response" = "404" ]; then
            echo "APP_EXISTS=false" >> $GITHUB_OUTPUT
          else
            echo "APP_EXISTS=true" >> $GITHUB_OUTPUT
          fi

      - name: Create app if it doesn't exist
        if: steps.check-app.outputs.APP_EXISTS == 'false'
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.SCALINGO_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            "${{ env.SCALINGO_API_URL }}/apps" \
            -d "{\"name\": \"${{ steps.get-app-name.outputs.APP_NAME }}\"}"

      - name: Add PostgreSQL addon if app was created
        if: steps.check-app.outputs.APP_EXISTS == 'false'
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.SCALINGO_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            "${{ env.SCALINGO_API_URL }}/apps/${{ steps.get-app-name.outputs.APP_NAME }}/addons" \
            -d '{
              "addon_provider": {
                "provider_id": "postgresql",
                "plan": "postgresql-sandbox"
              }
            }'

      - name: Set environment variables
        if: steps.check-app.outputs.APP_EXISTS == 'false'
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.SCALINGO_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            "${{ env.SCALINGO_API_URL }}/apps/${{ steps.get-app-name.outputs.APP_NAME }}/variables" \
            -d "{
              \"variables\": [
                {
                  \"name\": \"GH_TOKEN\",
                  \"value\": \"${{ secrets.GH_TOKEN }}\"
                },
                {
                  \"name\": \"GH_ENGINE_CONFIG_URL\",
                  \"value\": \"${{ github.server_url }}/${{ github.repository }}/raw/main/engine.config.json\"
                }
              ]
            }"

      - name: Get current package version
        id: get-version
        run: |
          CURRENT_VERSION=$(bun -e "console.log(require('./package.json').dependencies['@latechforce/engine'])")
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Get deployed version
        id: get-deployed-version
        run: |
          # Get deployments and store response
          DEPLOYMENTS_RESPONSE=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.SCALINGO_API_TOKEN }}" \
            "${{ env.SCALINGO_API_URL }}/apps/${{ steps.get-app-name.outputs.APP_NAME }}/deployments")

          # Debug: Print response (without sensitive data)
          echo "Deployments response: $(echo "$DEPLOYMENTS_RESPONSE" | jq -r '.')"

          # Check if response is empty or invalid
          if [ -z "$DEPLOYMENTS_RESPONSE" ] || [ "$DEPLOYMENTS_RESPONSE" = "null" ]; then
            echo "No deployments found"
            echo "DEPLOYED_VERSION=null" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Get the first deployment's git_ref
          DEPLOYED_VERSION=$(echo "$DEPLOYMENTS_RESPONSE" | jq -r '.deployments[0].git_ref // empty')

          if [ -z "$DEPLOYED_VERSION" ]; then
            echo "No deployment version found"
            echo "DEPLOYED_VERSION=null" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Get package.json from the deployment
          PACKAGE_JSON_RESPONSE=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.SCALINGO_API_TOKEN }}" \
            "${{ env.SCALINGO_API_URL }}/apps/${{ steps.get-app-name.outputs.APP_NAME }}/deployments/$DEPLOYED_VERSION/package.json")

          # Debug: Print package.json response (without sensitive data)
          echo "Package.json response: $(echo "$PACKAGE_JSON_RESPONSE" | jq -r '.')"

          # Extract engine version
          DEPLOYED_PACKAGE_VERSION=$(echo "$PACKAGE_JSON_RESPONSE" | jq -r '.dependencies["@latechforce/engine"] // empty')

          if [ -z "$DEPLOYED_PACKAGE_VERSION" ]; then
            echo "No engine version found in package.json"
            echo "DEPLOYED_VERSION=null" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "DEPLOYED_VERSION=$DEPLOYED_PACKAGE_VERSION" >> $GITHUB_OUTPUT

      - name: Check if version changed
        id: check-version
        run: |
          if [ "${{ steps.get-version.outputs.CURRENT_VERSION }}" != "${{ steps.get-deployed-version.outputs.DEPLOYED_VERSION }}" ]; then
            echo "VERSION_CHANGED=true" >> $GITHUB_OUTPUT
          else
            echo "VERSION_CHANGED=false" >> $GITHUB_OUTPUT
          fi

      - name: Deploy if version changed
        if: steps.check-version.outputs.VERSION_CHANGED == 'true'
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.SCALINGO_API_TOKEN }}" \
            "${{ env.SCALINGO_API_URL }}/apps/${{ steps.get-app-name.outputs.APP_NAME }}/deployments" \
            -d "{\"git_ref\": \"${{ github.sha }}\"}"

      - name: Run build:config if version unchanged
        if: steps.check-version.outputs.VERSION_CHANGED == 'false'
        run: bun run build:config

      - name: Commit config changes
        if: steps.check-version.outputs.VERSION_CHANGED == 'false'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./engine.config.json
          git commit -m "chore: update engine config" || exit 0
          git push

      - name: Restart app if version unchanged
        if: steps.check-version.outputs.VERSION_CHANGED == 'false'
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.SCALINGO_API_TOKEN }}" \
            "${{ env.SCALINGO_API_URL }}/apps/${{ steps.get-app-name.outputs.APP_NAME }}/restart"
