name: Deploy to Scalingo

on:
  workflow_run:
    workflows: ['Release']
    types:
      - completed

env:
  SCALINGO_API_URL: https://api.osc-fr1.scalingo.com/v1
  SCALINGO_AUTH_URL: https://auth.scalingo.com/v1

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    name: Deploy to Scalingo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Get app name from package.json
        id: get-app-name
        run: |
          APP_NAME=$(bun -e "console.log(require('./package.json').name)")
          echo "APP_NAME=$APP_NAME" >> $GITHUB_OUTPUT

      - name: Get Bearer Token
        id: get-bearer-token
        run: |
          # Get the Bearer token
          BEARER_TOKEN_RESPONSE=$(curl -s \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -u ":${{ secrets.SCALINGO_API_TOKEN }}" \
            -X POST "${{ env.SCALINGO_AUTH_URL }}/tokens/exchange")

          echo "Bearer token response: $BEARER_TOKEN_RESPONSE"

          # Extract the token
          BEARER_TOKEN=$(echo "$BEARER_TOKEN_RESPONSE" | jq -r '.token')

          if [ -z "$BEARER_TOKEN" ] || [ "$BEARER_TOKEN" = "null" ]; then
            echo "Failed to get Bearer token"
            exit 1
          fi

          echo "BEARER_TOKEN=$BEARER_TOKEN" >> $GITHUB_OUTPUT

      - name: Check if app exists on Scalingo
        id: check-app
        run: |
          # Debug: Print the Bearer token (first few characters)
          echo "Using Bearer token: ${BEARER_TOKEN:0:10}..."

          # Get the full response for debugging
          response=$(curl -s \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ steps.get-bearer-token.outputs.BEARER_TOKEN }}" \
            "${{ env.SCALINGO_API_URL }}/apps/${{ steps.get-app-name.outputs.APP_NAME }}")

          # Get the status code
          status_code=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ steps.get-bearer-token.outputs.BEARER_TOKEN }}" \
            "${{ env.SCALINGO_API_URL }}/apps/${{ steps.get-app-name.outputs.APP_NAME }}")

          echo "Status code: $status_code"
          echo "Response: $response"

          if [ "$status_code" = "404" ]; then
            echo "App does not exist (404)"
            echo "APP_EXISTS=false" >> $GITHUB_OUTPUT
          elif [ "$status_code" = "200" ]; then
            echo "App exists (200)"
            echo "APP_EXISTS=true" >> $GITHUB_OUTPUT
          else
            echo "Unexpected status code: $status_code"
            echo "APP_EXISTS=false" >> $GITHUB_OUTPUT
          fi

      - name: Create app if it doesn't exist
        if: steps.check-app.outputs.APP_EXISTS == 'false'
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ steps.get-bearer-token.outputs.BEARER_TOKEN }}" \
            -H "Content-Type: application/json" \
            "${{ env.SCALINGO_API_URL }}/apps" \
            -d "{\"name\": \"${{ steps.get-app-name.outputs.APP_NAME }}\"}"

      - name: Add PostgreSQL addon if app was created
        if: steps.check-app.outputs.APP_EXISTS == 'false'
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ steps.get-bearer-token.outputs.BEARER_TOKEN }}" \
            -H "Content-Type: application/json" \
            "${{ env.SCALINGO_API_URL }}/apps/${{ steps.get-app-name.outputs.APP_NAME }}/addons" \
            -d '{
              "addon": {
                "addon_provider_id": "postgresql",
                "plan_id": "5cc45d3e3e6b3b001249e5a5"
              }
            }'

      - name: Get current package version
        id: get-version
        run: |
          CURRENT_VERSION=$(bun -e "console.log(require('./package.json').dependencies['@latechforce/engine'].replace('^', ''))")
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Set environment variables
        if: steps.check-app.outputs.APP_EXISTS == 'false'
        run: |
          curl -X PUT \
            -H "Authorization: Bearer ${{ steps.get-bearer-token.outputs.BEARER_TOKEN }}" \
            -H "Content-Type: application/json" \
            "${{ env.SCALINGO_API_URL }}/apps/${{ steps.get-app-name.outputs.APP_NAME }}/variables" \
            -d "{
              \"variables\": [
                {
                  \"name\": \"GH_TOKEN\",
                  \"value\": \"${{ secrets.GH_TOKEN }}\"
                },
                {
                  \"name\": \"GH_ENGINE_CONFIG_URL\",
                  \"value\": \"${{ github.server_url }}/${{ github.repository }}/raw/main/engine.config.json\"
                },
                {
                  \"name\": \"LTF_ENGINE_VERSION\",
                  \"value\": \"${{ steps.get-version.outputs.CURRENT_VERSION }}\"
                }
              ]
            }"

      - name: Get deployed version
        id: get-deployed-version
        run: |
          # Get environment variables
          ENV_VARS_RESPONSE=$(curl -s \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ steps.get-bearer-token.outputs.BEARER_TOKEN }}" \
            "${{ env.SCALINGO_API_URL }}/apps/${{ steps.get-app-name.outputs.APP_NAME }}/variables")

          # Extract the engine version from environment variables
          DEPLOYED_VERSION=$(echo "$ENV_VARS_RESPONSE" | jq -r '.variables[] | select(.name == "LTF_ENGINE_VERSION") | .value')

          if [ -z "$DEPLOYED_VERSION" ] || [ "$DEPLOYED_VERSION" = "null" ]; then
            echo "No engine version found in environment variables"
            echo "DEPLOYED_VERSION=null" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "DEPLOYED_VERSION=$DEPLOYED_VERSION" >> $GITHUB_OUTPUT

      - name: Check if version changed
        id: check-version
        run: |
          if [ "${{ steps.get-version.outputs.CURRENT_VERSION }}" != "${{ steps.get-deployed-version.outputs.DEPLOYED_VERSION }}" ]; then
            echo "VERSION_CHANGED=true" >> $GITHUB_OUTPUT
          else
            echo "VERSION_CHANGED=false" >> $GITHUB_OUTPUT
          fi

      - name: Update engine version if changed
        if: steps.check-version.outputs.VERSION_CHANGED == 'true'
        run: |
          curl -X PUT \
            -H "Authorization: Bearer ${{ steps.get-bearer-token.outputs.BEARER_TOKEN }}" \
            -H "Content-Type: application/json" \
            "${{ env.SCALINGO_API_URL }}/apps/${{ steps.get-app-name.outputs.APP_NAME }}/variables" \
            -d "{
              \"variables\": [
                {
                  \"name\": \"LTF_ENGINE_VERSION\",
                  \"value\": \"${{ steps.get-version.outputs.CURRENT_VERSION }}\"
                }
              ]
            }"

      - name: Deploy if app doesn't exist or version changed
        if: steps.check-app.outputs.APP_EXISTS == 'false' || steps.check-version.outputs.VERSION_CHANGED == 'true'
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ steps.get-bearer-token.outputs.BEARER_TOKEN }}" \
            "${{ env.SCALINGO_API_URL }}/apps/${{ steps.get-app-name.outputs.APP_NAME }}/deployments" \
            -d "{
              \"deployment\": {
                \"git_ref\": \"${{ github.sha }}\",
                \"source_url\": \"${{ github.server_url }}/${{ github.repository }}/archive/${{ github.sha }}.tar.gz\"
              }
            }"

      - name: Run build:config if app exists
        if: steps.check-app.outputs.APP_EXISTS == 'true'
        env:
          NODE_ENV: production
        run: bun run build:config

      - name: Commit config changes
        if: steps.check-app.outputs.APP_EXISTS == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./engine.config.json
          git commit -m "chore: update engine config [skip ci]" || exit 0
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"

      - name: Restart app if app exists
        if: steps.check-app.outputs.APP_EXISTS == 'true'
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ steps.get-bearer-token.outputs.BEARER_TOKEN }}" \
            "${{ env.SCALINGO_API_URL }}/apps/${{ steps.get-app-name.outputs.APP_NAME }}/restart"
