name: Release

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    name: Run Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
            bun-version: 1.2.5
      - run: bun install
      - run: bun run lint
      - run: bun run build
      - run: bun run test

  release:
    name: Create Release
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
            bun-version: 1.2.5
      - run: bun install
      - run: bun run build
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: bunx semantic-release
      - name: Build Config
        run: bun run build:config
      - name: Commit Config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add engine.config.json
          git commit -m "chore: update engine config [skip ci]"
          git push
